// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Satur8.Persistence;

#nullable disable

namespace Satur8.Persistence.Migrations
{
    [DbContext(typeof(SaturatorDbContext))]
    [Migration("20260510114032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Satur8.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "validate_categories_name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Satur8.Domain.Models.Favourite", b =>
                {
                    b.Property<Guid>("FavouritesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("favourites_id");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FavouritesId")
                        .HasName("favourites_pkey");

                    b.HasIndex("PresetId");

                    b.HasIndex("UserId");

                    b.ToTable("favourites", (string)null);
                });

            modelBuilder.Entity("Satur8.Domain.Models.Preset", b =>
                {
                    b.Property<Guid>("PresetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("preset_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters_json");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PresetId")
                        .HasName("presets_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("presets", (string)null);
                });

            modelBuilder.Entity("Satur8.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Satur8.Domain.Models.Favourite", b =>
                {
                    b.HasOne("Satur8.Domain.Models.Preset", "Preset")
                        .WithMany("Favourites")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favourites_preset_id_fkey");

                    b.HasOne("Satur8.Domain.Models.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favourites_user_id_fkey");

                    b.Navigation("Preset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Satur8.Domain.Models.Preset", b =>
                {
                    b.HasOne("Satur8.Domain.Models.Category", "Category")
                        .WithMany("Presets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("presets_category_id_fkey");

                    b.HasOne("Satur8.Domain.Models.User", "User")
                        .WithMany("Presets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("presets_user_id_fkey");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Satur8.Domain.Models.Category", b =>
                {
                    b.Navigation("Presets");
                });

            modelBuilder.Entity("Satur8.Domain.Models.Preset", b =>
                {
                    b.Navigation("Favourites");
                });

            modelBuilder.Entity("Satur8.Domain.Models.User", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("Presets");
                });
#pragma warning restore 612, 618
        }
    }
}
